### ISSUE TITLE
Mocking 'unpaid' subscriptions

### ISSUE THREAD

**Issue by bradleesand** [stripe-ruby-mock/stripe-ruby-mock#111]
There doesn't seem to be any way to mock an unpaid subscription.

**Comment by MikeIsMe** [comment]
Yes, I'm seeing an exception thrown in the response back to a Customer.create() for a plan with a trial period but no card info yet, which is a valid way to use Stripe.  The exception is stating that there is no valid card.

Any thoughts on how to do this or is this a known limitation?

Thanks

**Comment by MikeIsMe** [comment]
OK, I think I found a workaround, at least for my situation.  By adding "trial_period_days: 1" to the plan definition, then StripeMock allows a subscription without a credit to be created.

Hope that helps someone.
