### ISSUE TITLE
Per-Subscription Discounts

### ISSUE THREAD

**Issue by mbleigh** [stripe-ruby-mock/stripe-ruby-mock#126]
The mock library doesn't seem to take into account that discounts can be applied per-subscription. I ran into this when `subscription.discount` was a NoMethodError, but it may also appear when creating a subscription (it should take the `coupon` param).

https://stripe.com/docs/api#create_subscription

**Comment by nbrustein** [comment]
Yes, I have confirmed that passing a coupon param to Stripe::Subscription.create does not work as expected.  No discount is applied to the subscription
