### ISSUE TITLE
Calling update_subscription results in 'No such customer' exception

### ISSUE THREAD

**Issue by johnathanludwig** [stripe-ruby-mock/stripe-ruby-mock#142]
I am doing the following

``` ruby
customer = Stripe::Customer.create(email: 'johnny@appleseed.com',
                                   card: StripeMock.generate_card_token(last4: '9191'))
Stripe::Plan.create(id: 'abc', amount: 123, interval: 'month', currency: 'usd', name: 'test1')
customer.update_subscription(plan: 'abc')
```

The `update_subscription` call is throwing the exception:
Stripe::InvalidRequestError: No such customer: test_cus_3/subscription

Calling `update_subscription` on a customer works well with the stripe-ruby SDK.

**Comment by ChrisCPO** [comment]
So this issue is not quite resolved, updating a subscription.plan via the stripe docs way still results in a weird error. 

docs:
```ruby
subscription = Stripe::Subscription.retrieve({SUBSCRIPTION_ID})
subscription.plan = {PLAN_ID}
subscription.save
```
my code:
```ruby
      stripe_sub = user.subscription.stripe_self
      stripe_sub.plan = plan_id
      stripe_sub.save
```
error:    
Stripe::InvalidRequestError:
   No such customer: test_cus_3/subscriptions/test_su_4

**Comment by Sohair63** [comment]
Having same issue https://github.com/rebelidealist/stripe-ruby-mock/issues/142#issuecomment-230622814

**Comment by Sohair63** [comment]
The doc has this thing mentioned in here: 
https://stripe.com/docs/billing/subscriptions/canceling-pausing#reactivating-canceled-subscriptions
```
If the cancellation has already been processed and the subscription is no longer active, a new subscription is needed for the customer. Keep in mind that Stripe immediately starts your customer’s subscription under a new billing cycle, so this action results in a new charge. You can override this behavior using the trial_end parameter so the customer isn’t immediately billed (e.g., to maintain the old billing cycle).
```
