### ISSUE TITLE
Feature Request to add ability to un-cancel a subscription

### ISSUE THREAD

**Issue by latuprez** [stripe-ruby-mock/stripe-ruby-mock#146]
Sorry if I am being a bother with a second feature request but I also would love the ability to test un-cancelling a subscription that has cancel_at_period_end: true . Stripe asserts that to do this you must retrieve the subscription then set the plan to the ID of your plan and then save. When I do this through the Stripe Mock Server my cancel_at_period_end doesn't change but when I manually run my action to un-cancel a subscription it does indeed work. Stripe's discussion of how to achieve what I need is here: https://support.stripe.com/questions/how-can-i-resume-a-subscription-after-it-has-been-canceled

**Comment by theoretick** [comment]
Strange, I just filed a support request with stripe recently about this and got a negative response:
```
Hi Lucas,

Thanks for writing. Unfortunately as you discovered there is no way to uncancel a subscription right now. But! Since it's still available to retrieve you can pretty easily make a new subscription that is just like it. You can use a super secret undocumented parameter 'billing_cycle_anchor' to specify the same billing date as the old subscription, possibly with a trial_end set appropriately to delay the first payment, to essentially transparently replace the subscription with a new one.

Makes sense? Let me know if I can answer any more questions.

Cheers,
Ryan﻿
```
