### ISSUE TITLE
Can't get feature specs to hit the mock server.

### ISSUE THREAD

**Issue by yjukaku** [stripe-ruby-mock/stripe-ruby-mock#148]
I'm using Capybara with a Selenium driver to submit a Stripe form in my feature specs. I can see that the requests aren't hitting the mock server at all.  I've tried to do both `StripeMock.start` & the other way, `StripeMock.start_client`

Is there something I'm missing to get feature specs working?

**Comment by byterussian** [comment]
Same situation, the gem handles every request from the backend but in the frontend 'https://api.stripe.com/v1/tokens' isn't intercepted.

**Comment by brianhempel** [comment]
There's two problems here:

1. Your local machine needs to intercept the requests going to `api.stripe.com`.
2. Your local machine needs to bypass SSL somehow. The whole point of SSL is that you cannot pretend to be someone you are not. If the browser is trying to hit `https://api.stripe.com`, and `api.stripe.com` responds with a certificate that is not signed by a trusted authority, the request will die. I tried to do a MITM attack on my test server by self-signing a certificate and telling the browser to trust it, but I could not get it to work for whatever reason.

Neither of these problems are easy to solve cleanly. The best solution might be some thing that scrubs your Rails responses, replacing the string `https://api.stripe.com` with some `http://localhost` or something similar.

**Comment by yjukaku** [comment]
I think this is somewhat solvable, although I ended up just trying to work around it.

Instead of scrubbing out Rails responses, one would need to replace calls to https://api.stripe.com with the address of our local Stripe server.

Not sure how to do that, and it's not worth my time for now.  

In the meanwhile I've resorted to getting real tokens from the browser, then mocking the responses to my backend requests using WebMock.

**Comment by stevehanson** [comment]
@yjukaku: Thanks for sharing your experience. I'm having the same issue, and I'm fine with just letting my browser get real tokens, but I'm getting this JS error in my Capybara test:

```
XMLHttpRequest cannot load https://api.stripe.com/v1/tokens. Origin https://js.stripe.com is not allowed by Access-Control-Allow-Origin.", :source=>"https://js.stripe.com/v2/channel.html?stripe_xdm_e=http%3A%2F%2F127.0.0.1%3A55210&stripe_xdm_c=default817163&stripe_xdm_p=1#__stripe_transport__
```

Did you get that error, too, and if so, how did you work around it?

**Comment by mattvanhorn** [comment]
`Stripe.endpoint = 'localhost:4999'` seems to control the endpoint, but I am still having trouble getting the server to respond to requests properly.

**Comment by yjukaku** [comment]
@stevehanson Sorry, I don't remember anymore!

@mattvanhorn Nice find with the `Stripe.endpoint`.  So are you just running javascript from the spec to set that variable? Also, what trouble are you having?

**Comment by stevehanson** [comment]
Here's the solution I went with, which is admittedly a little messy. 

First, I set the token as an ENV variable in my test:

```rb
ENV["STRIPE_TOKEN"] = stripe_helper.generate_card_token(last_4: '4242', exp_year: '2025', exp_month: '12')
```

And inject the fake token into the page:

```erb
<% if Rails.env.test? && ENV["STRIPE_TOKEN"] %>
  <div id="js_test_token"><%= ENV["STRIPE_TOKEN"] %></div>
<% end %>
```

and then in my JS form submit handler, I bypass the Stripe call if the token is present on the page:

```js
var self = this;

if($('#js_test_token').length) { // mock stripe call in feature tests
  setTimeout(function() { self.stripeResponseHandler('success', { id: $('#js_test_token').text() }); }, 0);
} else {
  Stripe.card.createToken({
    number: $form.find('#cc_number').val(),
    cvc: $form.find('#cc_cvc').val(),
    exp: $form.find('#cc_exp').val(),
    address_zip: $form.find('#cc_postal_code').val()
  }, self.stripeResponseHandler.bind(self));
}
```

This way, in my feature tests, I bypass the Stripe call and just invoke the handler with the token generated by _stripe-ruby-mock_.

**Comment by mattvanhorn** [comment]
I was trying to set it by executing javascript w/ capybara. We gave up on mocking everything, because we needed to move faster, but when I go back to it, I will post updates here.

**Comment by mattvanhorn** [comment]
@stevehanson - that was going to be my fallback approach, I don't love having "if test" conditionals in my code, but if it works, that's at least an option.

**Comment by stevehanson** [comment]
@mattvanhorn executing JS with capybara seems like a much better idea. Didn't think of that. I bet something like this would work:

```
page.execute_script "window.testStripeToken = '#{my_token}';"
```

and then can just check `if(window.testStripeToken)` in the Stripe JS code. That's a little cleaner. No need for anything in the DOM. I agree that it still sucks to have to have conditionals or that the code has to know about testing at all. Still a little better than not having tests over a critical part of our app, though :)

**Comment by naw** [comment]
For anyone stumbling on this, I want to point out that setting `Stripe.endpoint` to a different endpoint (such as a fake local server) is not officially supported by `Stripe.js`.   This _did_ work until recently, but `Stripe.js` recently changed, and setting `Stripe.endpoint` doesn't necessary have any effect on the server that `Stripe.js` hits anymore.  Therefore, if you really want to hit a fake server, you'll need to use some mechanism other than just setting `Stripe.endpoint`.
