### ISSUE TITLE
Issue with Stripe::Token

### ISSUE THREAD

**Issue by melcher** [stripe-ruby-mock/stripe-ruby-mock#52]
Trying to create a stripe token like so:

``` ruby
Stripe::Token.create({
      card: {
        number: "4222222222222222",
        exp_month: '09',
        exp_year: 2.years.since.year.to_s, # e.g. '2017'
      }
    })
```

Should return a Stripe::Token object with an `#id` method, which is the token id. Instead it returns:

```
#<Stripe::StripeObject:0x3fc738d8db48> JSON: {}
```

Not sure if I'm using this incorrectly or if Stripe::Token hasn't been implemented yet.
Thanks,
- Graham

**Comment by jackphelps** [comment]
This thread was helpful, thanks everyone. 

I felt that for my purposes this was a little complex; I'm using Rails and found it pretty quick to basically fake Stripe.js's Stripe object when in test. I'm using rails and found it pretty quick to just swap out my Stripe.js script call in the template to a custom helper that looks roughly like this:
```
  def stripe_js_script_code
    if Rails.env.test?
      test_script     = helpers.javascript_include_tag 'stripe_test', "data-turbolinks-track" => true
      fake_token_meta = '<meta name="fake-stripe-token" content="' + StripeMock.generate_card_token() + '">'
      return fake_token_meta + test_script
    else
      '<script src="https://js.stripe.com/v2/" data-turbolinks-track="false"></script>'
    end
  end
```
My script looks like this:
https://gist.github.com/jackphelps/4b4f98ca8c314cb86bc7

(the meta could easily be js, it was just quicker and easier this way so I didn't have to override my security policy)

**Comment by georgemillo** [comment]
I've tried all of above, but my tests simply won't call my FakeStripe implementation.

`console.log(Stripe.endpoint)` outputs `http://127.0.0.1:54832/v1`

A `puts` statement within `FakeStripe` tells me that my Capybara Server is listening at `http://127.0.0.1:54832`

Loading up `FakeStripe` independently of the tests and visiting `http://127.0.0.1:54832` within the browser shows me that my `/v1/tokens` endpoint is working fine (POST and GET)

`console.log`s within my Javascript tell me that things work fine and the following code is executed:

      Stripe.createToken({
        number:    $("#card_number").val(),
        cvc:       $("#card_cvc").val(),
        exp_month: $("#card_expiry_month").val(),
        exp_year:  $("#card_expiry_year").val()
      }, stripeResponseHandler);

But it's not calling `FakeStripe` (and, judging by the logs in my Stripe dashboard, it's not calling the 'real' Stripe either... although it works fine when I'm manually testing things in development mode.) And my `stripeResponseHandler` never gets called back either.

What am I doing wrong?

**Comment by georgemillo** [comment]
Maybe significant... @gyardley's code above is using **v1** of the code from js.stripe.com. I'm using v2. Could this have broken things?
