### ISSUE TITLE
As of version 2018-02-05, plan's statement_descriptor and name fields moved to product

### ISSUE THREAD

**Issue by pwim** [stripe-ruby-mock/stripe-ruby-mock#546]
The attributes used to create a plan object changed with [2018-02-05](https://stripe.com/docs/upgrades#2018-02-05):

> Each plan object is now linked to a product object with `type=service`. The plan object fields `statement_descriptor` and `name` attributes have been [moved to product](https://stripe.com/docs/api#product_object-statement_descriptor) objects. Creating a plan now requires passing a [product attribute](https://stripe.com/docs/api#create_plan-product) to `POST /v1/plans`. This may be either an existing product ID or a dictionary of product fields, so that you may continue to create plans without separately creating products.

There are currently two outstanding PRs regarding this, both with failing tests:
* #536 Support for API change for 2018-02-06
* #515 Support Product for API change for 2018-02-06

**Comment by charlespeach** [comment]
Would love to see one or both of those merged. Currently cannot use StripeMock with plans at all
