### ISSUE TITLE
stripe API working fine on localhost but its not working on server? please reply

### ISSUE THREAD

**Issue by tauqeer01** [stripe-ruby-mock/stripe-ruby-mock#657]
i have integrated Stripe using asp.net core for shopping cart. i tested its working fine on local host but as i uploaded on server and test live there is no error but its not making any transaction in stripe account . please reply

**Comment by iCreateJB** [comment]
This library is for mocking the stripe interface for testing purposes... I believe you may be looking for https://github.com/stripe/stripe-dotnet.

**Comment by MrBns** [comment]
I am using it with Javascript and Firebase Serverless Function. But not working.  its says API keys are not varid. But when I tried it on Local server it works fine.
Any Idea about it ?

**Comment by TastyPi** [comment]
@MrBns this issue is 4 years old, and it sounds like you want support about the real Stripe API. This is an unofficial mock implementation of the Stripe API used for writing tests in Ruby, please redirect your question to Stripe's support.
