### ISSUE TITLE
What has changed in version 3.x?

### ISSUE THREAD

**Issue by kylefox** [stripe-ruby-mock/stripe-ruby-mock#680]
Because this project [does not have a changelog](https://github.com/rebelidealist/stripe-ruby-mock/issues/532) would it be possible to summarize what has changed in the 3.x release? According to the README's [versioning system](https://github.com/rebelidealist/stripe-ruby-mock#versioning-system):

> The major number (1.x.x) is for breaking changes involving how you use StripeMock itself

Presumably the version bump from 2.x → 3.x means there are breaking, backwards-incompatible changes.

I understand that maintaining a detailed changelog of minor/patch versions can be tedious, but at the very least it would idea to provide a description of backwards-incompatible changes — even if very high-level and brief.

Thanks!

**Comment by ioki-klaus** [comment]
My PR #658 was the cause for the major bump.

Stripe gem 5.0.0 changed the signature for Error constructors and this PR updated to that signature. So, version 3.0.0 of this gem is not compatible with stripe gem < 5.0.

Sorry for not adding something to README.

**Comment by kylefox** [comment]
OK, thanks for letting me know! A changelog might be a useful addition to this project, but I realize they can be a lot of work to maintain.

**Comment by alexmamonchik** [comment]
added small [description](https://github.com/stripe-ruby-mock/stripe-ruby-mock#-important). Yes, will be nice to create and support changelog.
