### ISSUE TITLE
Unable to refund a payment intent 

### ISSUE THREAD

**Issue by amex-doug** [stripe-ruby-mock/stripe-ruby-mock#714]
I am getting this error from this code

```
     Stripe::InvalidRequestError:
       No such charge:
```

```
let(:payment_intent) {  Stripe::PaymentIntent.create(amount:  100, currency: "jpy", confirm: true) }

Stripe::Refund.create({ payment_intent: payment_intent.id })

```

**Comment by stefatkins** [comment]
I'm having the same issue here.

**Comment by connor-t** [comment]
running this test gives the same error `Stripe::InvalidRequestError:
       No such charge:`
```
payment_intent = Stripe::PaymentIntent.create(
        amount: 999,
        currency: 'USD'
      )

      refund = Stripe::Refund.create(
        payment_intent: payment_intent.id
      )
      expect(refund.amount).to eq(999)
```

**Comment by tbhockey** [comment]
Why was this closed? I'm also having the same issue

**Comment by TastyPi** [comment]
I believe it is fixed at head, but there hasn't been a new release in a long time. Can you try it from head and see if it works?

**Comment by tbhockey** [comment]
> I believe it is fixed at head, but there hasn't been a new release in a long time. Can you try it from head and see if it works?

Sure enough, that seems to work. thx @TastyPi
