### ISSUE TITLE
Subscription is missing default_payment_method field

### ISSUE THREAD

**Issue by matthewmcgarvey** [stripe-ruby-mock/stripe-ruby-mock#716]
Looking through the API changelog, it doesn't look like it was added later than this library supports.

It is an expandable field that is assigned.
API reference: https://stripe.com/docs/api/subscriptions/object#subscription_object-default_payment_method

**Comment by rpietraszko** [comment]
This PR should resolve this:
https://github.com/stripe-ruby-mock/stripe-ruby-mock/pull/720
