### ISSUE TITLE
Ruby 2.7 deprecation warning

### ISSUE THREAD

**Issue by jacobjlevine** [stripe-ruby-mock/stripe-ruby-mock#725]
Relevant stack/libraries:
stripe-ruby-mock - 3.0.1
Rails - 6.0.3.1
Ruby - 2.7.1

Running my test suite since upgrading to Ruby 2.7 yields the following warning message:
lib/stripe_mock/api/instance.rb:10: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

**Comment by crispinheneise** [comment]
I'm also getting...

```
~/.gem/ruby/2.7.1/gems/stripe-ruby-mock-3.0.1/lib/stripe_mock/api/instance.rb:12: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
~/.gem/ruby/2.7.1/gems/stripe-ruby-mock-3.0.1/lib/stripe_mock/instance.rb:103: warning: The called method `mock_request' is defined here
```

**Comment by jacobjlevine** [comment]
Oh, one thing to add from my research elsewhere. The two errors that @crispinheneise mentioned are actually a pair that refer to the same issue (the warning I reported had a similar second message which I didn't include for reasons below). The first warning shows the line with the method call that needs to be updated. The second warning identifies the method being called.

This was a terrible design decision in Ruby 2.7 because it definitely makes it seem as though there are 2 separate issues (and it's even more confusing if the first and second warnings come from separate gems).

I'm a little delirious right now, but hope that makes sense!

**Comment by crispinheneise** [comment]
This may not be related, but I'm also getting a TypeError with any `create` method: 

```rb
irb(main):001:0> StripeMock.start
=> "local"
irb(main):002:0> stripe_helper = StripeMock.create_test_helper
irb(main):003:0>
irb(main):004:2* customer = Stripe::Customer.create({
irb(main):005:2*     email: 'johnny@appleseed.com',
irb(main):006:2*     source: stripe_helper.generate_card_token
irb(main):007:0>   })
Traceback (most recent call last):
        1: from (irb):5
TypeError (no implicit conversion of Array into Hash)
irb(main):008:0>
```

There is no stack trace. I haven't taken the time yet to track this down. 

Again, not sure if this is related to the deprecation warnings, but there seem to be some breaking changes with Ruby 2.7. Should this be split into a separate issue?
