### ISSUE TITLE
Stripe has replaced Plans API with Prices API 

### ISSUE THREAD

**Issue by mitya** [stripe-ruby-mock/stripe-ruby-mock#753]
Hey guys,

It seems that Stripe is deprecating Plans API and introduces Prices API instead. it will be great if stripe-ruby-mock supports the new API.

https://stripe.com/docs/payments/checkout/migrating-prices

Thank you

**Comment by zokioki** [comment]
Looks like there's a pending PR for this in https://github.com/stripe-ruby-mock/stripe-ruby-mock/pull/730, hopefully will make it in soon.

**Comment by csalvato** [comment]
#730 has been merged. If you need this immediately, please reference the `master` branch in your gem file until we do an official release.

```rb
gem 'stripe-ruby-mock', require: 'stripe_mock', git: 'https://github.com/stripe-ruby-mock/stripe-ruby-mock', branch: 'master'
```
