### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by csalvato** [stripe-ruby-mock/stripe-ruby-mock#763]
It's totally cool if it has been, just wondering if the contributors have time to maintain this, or is it at risk of falling into obscurity?

There's a few things pointing to the project being abandoned:

1. The gem is now incompatible with Ruby 3, and two PRs that bring this up to date have been ignored for months.
2. The Plans API has been deprecated by Stripe, but this repo doesn't support the Prices API, and the PR that brings this up to date has been ignored.
3. This repo does not support Stripe Connect, and the PR that enables support for it has been ignored.
4. There are 60 open PRs that haven't been addressed or closed.
5. There are 140 issues open, and only 5 were closed in the past 12 months
6. The specs on `master` don't pass (at least when I run them locally).
7. Messages on the gitter go unanswered, even by those asking to be contributors.

I feel like this gem was extremely helpful for those using Stripe, but it's becoming useless unless an update happens pretty soon.

No offense intended by any of this - just looking to make progress on my own projects, and build on the great work which is already in this repo.

There seems to be a community of devs who want to contribute and maintain this repo. So I think there's three options:

1. @alexmamonchik @gilbert or other folks with write access need to address the open PRs/issues.
2. @alexmamonchik @gilbert or admins need to add some other people with the power to merge into `master`
3. The community can fork this repo and maintain it (similar to what happened to the `fast_jsonapi` gem that was started by Netflix but taken over by the community)

I would love for this to all stay in one repo and not fracture the community.  

Is it possible for 1 or 2 to happen?

**Comment by nimashariatian** [comment]
I agree with @csalvato , if the maintainers are feeling burned or overwork, please let the community take over , thank you for all the hard work folks!

**Comment by alexmamonchik** [comment]
@nimashariatian @csalvato have you read https://github.com/stripe-ruby-mock/stripe-ruby-mock#request-looking-for-more-core-contributors ? I don't have enough time for that and it breaks my hurt. If anybody wants to help - welcome!

**Comment by csalvato** [comment]
@alexmamonchik thanks again for all your work on this library so far.

Yes I've read that link, and followed the instructions:

> submit a significant enough pull request and have it merged into master (many of you have already done this). Afterwards, ping @gilbert in chat and I will add you as a collaborator.

But my PRs have been rotting on the vine for a few weeks, as well as several others that would modernize the library.

Is it possible for you to give me or some other people who are potential contributors the right to open and merge PRs into `master`?

**Comment by gilbert** [comment]
Hey @csalvato, sorry for the bad response times. Your PRs look good. I've sent you a collaborator invite.

**Comment by csalvato** [comment]
@gilbert No worries.

I merged in several PRs that fix issues I've been facing personally, and others in the community.

I created a pre-release 3.1.0.rc1 release tag in the repo.

Now, all we need to do is update the gem for people to use it.  Can you publish the gem, or add me as a gem owner so I can do it?

`gem owner stripe-ruby-mock --add csalvato` should work, to add me, I think.

**Comment by csalvato** [comment]
cc @alexmamonchik  ☝🏼

**Comment by gilbert** [comment]
@csalvato Added.

**Comment by csalvato** [comment]
> @csalvato Added.

Sorry @gilbert i was away on vacation when you added me :(

It looks like the token they sent me expired. Possible for you to resend it?

**Comment by gilbert** [comment]
@csalvato Running the command again errored with `Adding csalvato: User has already been taken`, but I was able to remove and re-add you.

**Comment by csalvato** [comment]
> @csalvato Running the command again errored with `Adding csalvato: User has already been taken`, but I was able to remove and re-add you.

That did the trick, thanks!

**Comment by csalvato** [comment]
Since it's not abandoned, I'm closing this issue.
