### ISSUE TITLE
Missing 'charge.refund.updated' webhook event

### ISSUE THREAD

**Issue by thdurante** [stripe-ruby-mock/stripe-ruby-mock#780]
Missing support for the `'charge.refund.updated'` webhook event.
https://stripe.com/docs/api/events/types#event_types-charge.refund.updated

**Comment by RichStone** [comment]
Hey @thdurante, I see this one is not supported yet, but I'm curious, do all other webhook events work for you like `payment_intent.succeeded`? (#819)

**Comment by rbclark** [comment]
I believe I added this as part of https://github.com/stripe-ruby-mock/stripe-ruby-mock/pull/825 so this should be in the next release.

**Comment by thdurante** [comment]
> Hey @thdurante, I see this one is not supported yet, but I'm curious, do all other webhook events work for you like payment_intent.succeeded? (https://github.com/stripe-ruby-mock/stripe-ruby-mock/issues/819)

hi @RichStone, yes! (sorry for the late reply)

**Comment by PelagicDev** [comment]
@thdurante You can close this issue since this is resolved by #825
