### ISSUE TITLE
undefined method `price' for #<Stripe::SubscriptionItem:0x00007f883d67a328>

### ISSUE THREAD

**Issue by miguelperez** [stripe-ruby-mock/stripe-ruby-mock#781]
What is the best way to handle these cases where the stripe API is updated and the schema changes?

```
     NoMethodError:
       undefined method `price' for #<Stripe::SubscriptionItem:0x00007f883d67a328>
```

As per the stripe documentation, the subscription item has the price information. But it seems the schema of the gem is using the version with `plan` instead. I understand that changing this directly will impact projects still on a previous stripe API version.

**Comment by shafy** [comment]
Any update when this will be merged into a release? As I can see, this is not part of release 3.1.0.rc3 yet?

**Comment by shoe** [comment]
@TastyPi Would you be able to cut a gem release with this fix? :pray:
