### ISSUE TITLE
`payment_intent.succeeded` is a supported webhook but getting StripeMock::UnsupportedRequestError (Unsupported webhook event `payment_intent.succeeded` (Searched in ./spec/fixtures/stripe_webhooks/))

### ISSUE THREAD

**Issue by RichStone** [stripe-ruby-mock/stripe-ruby-mock#819]
Running on the latest versions, `payment_intent.succeeded` does not work when trying to construct a `StripeMock.mock_webhook_event("payment_intent.succeeded")` event but some events work (e.g. `StripeMock.mock_webhook_event("charge.refunded")`

```
    stripe (5.43.0)
    stripe-ruby-mock (3.0.1)
      dante (>= 0.2.0)
      multi_json (~> 1.0)
      stripe (> 5, < 6)
```

![Screenshot 2022-02-17 at 16 09 33](https://user-images.githubusercontent.com/15954169/154511247-aae5b406-5603-41be-b53b-d42847ce794d.png)

**Comment by TastyPi** [comment]
3.0.1 is a fairly old version of this library, even though it is the one listed in the README. Consider using HEAD instead, this library's maintainers don't have the resources to do proper release cycles so a lot of fixes and improvements have been made (such as adding `payment_intent.succeeded` support) but not in any releases. You can add this to your Gemfile to get the latest commit:

```
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "stripe-ruby-mock", github: "stripe-ruby-mock/stripe-ruby-mock"
```

**Comment by RichStone** [comment]
> 3.0.1 is a fairly old version of this library, even though it is the one listed in the README. Consider using HEAD instead, this library's maintainers don't have the resources to do proper release cycles so a lot of fixes and improvements have been made (such as adding `payment_intent.succeeded` support) but not in any releases. You can add this to your Gemfile to get the latest commit:
> 
> ```
> git_source(:github) { |repo| "https://github.com/#{repo}.git" }
> 
> gem "stripe-ruby-mock", github: "stripe-ruby-mock/stripe-ruby-mock"
> ```

Thank you so much @TastyPi, this works perfectly fine now 🙏
