### ISSUE TITLE
Wrong no of arguments issue while mocking create  Stripe::Token.create.

### ISSUE THREAD

**Issue by talhaijaz** [stripe-ruby-mock/stripe-ruby-mock#832]
Getting ArgumentError: wrong number of arguments (given 3, expected 2)
My stripe version is 5.28.0 and stripe-ruby-mock 3.0.1.
Note i have tried to downgrade it but with downgrading stripe for stripe-ruby-mock excludes some of the features. That i need.

**Comment by talhaijaz** [comment]
@adamstegman @istro-omg Can you please guide. Thanks.

**Comment by istro-omg** [comment]
@talhaijaz neither me nor Adam are maintainers of this project, so we might not be best people to ask :-). StackOverflow might be a better place, as a lot more people would see it. Also, when you post a question I'd suggest including the few lines of code pertinent to the question, it might help folks spot the issue.

To point you in the general direction - I don't think you need to manually mock `Stripe::Token.create` - it looks like there's a helper function [here](https://github.com/stripe-ruby-mock/stripe-ruby-mock/blob/master/lib/stripe_mock/test_strategies/base.rb#L62-L69), referenced straight from [the readme](https://github.com/stripe-ruby-mock/stripe-ruby-mock#test-helpers).

**Comment by talhaijaz** [comment]
Thanks for feedback. I tried with helper function too but same issue. I will try stackoverflow then.

**Comment by aarkerio** [comment]
I had the same problem, apparently the problem is in the file:  

stripe-ruby-mock-3.0.1/lib/stripe_mock/api/instance.rb

Bundle downloaded the 3.0.1 version with the code:

    `Stripe::StripeClient.send(:define_method, :execute_request) { |*args| instance.mock_request(*args) }`   

 which is an old version, not compatible with Ruby 3. 

Setting the version 3.1.0.rc3 on my bundle fixed the problem.
