### ISSUE TITLE
Mocking 'checkout.session.completed' giving undefined method `exists?' for File:Class

### ISSUE THREAD

**Issue by buckled0** [stripe-ruby-mock/stripe-ruby-mock#873]
As the title suggests I'm trying to test the webhook `checkout.session.completed` but each time it runs I'm getting the following error:
```
NoMethodError:
       undefined method 'exists?' for File:Class
```
Here is my test code, it looks like what the docs give me but I can't seem to get it to work:
```
let(:event) do
      StripeMock.mock_webhook_event('checkout.session.completed', {
        client_reference_id: client.reference_id,
        subscription: subscription.id,
        customer_details: { email: user.email }
      })
    end
```
Currently using version `3.1.0.rc2`

**Comment by gregmolnar** [comment]
@buckled0 Could you please try this on master?

**Comment by codrutzu** [comment]
File.exists? was removed in ruby 3.2

https://github.com/ruby/ruby/commit/bf97415c02b11a8949f715431aca9eeb6311add2
